core/src/main/java/org/apache/shiro/session/mgt/AbstractValidatingSessionManager.java, core/src/test/java/org/apache/shiro/session/mgt/DefaultSessionManagerTest.java
If a SessionValidationScheduler was set via sessionManager.setSessionValidationScheduler, instead of using the
default creation of the object in enableSessionValidation, the SessionValidationScheduler would not be enabled.
=> SHIRO-577 Fixes bug allow enabling of SessionValidationScheduler when set via setSessionValidationScheduler

web/src/main/java/org/apache/shiro/web/mgt/DefaultWebSecurityManager.java, web/src/main/java/org/apache/shiro/web/mgt/DefaultWebSubjectFactory.java, web/src/test/java/org/apache/shiro/web/mgt/DefaultWebSecurityManagerTest.java, web/src/test/java/org/apache/shiro/web/mgt/NonIniWebSecurityManagerTest.java
Added: Test to login a DelegatingSubject on a programatically created DefaultWebSecurityManager
Fixed: DefaultWebSessionStorageEvaluator now has a SessionManager set when a DefaultWebSecurityManager is created though its noargs constructor.
Fixed: DefaultWebSubjectFactory now checks if its existing subject is indeed a WebSubject, and if not delegates to its supermethod. This avoids WebSubjects with null ServletRequest/Response.
=> SHIRO-646 Allow a DelegatingSubject to login Statelessly on a DefaultWebSecurityManager

tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java
The options for controlling the generated public salt were all
incorrectly documented.
=> Fix Hasher's help output.

support/guice/pom.xml
shiro-guice has a direct dependency on commons-beanutils (via `ShiroModule` -> `BeanTypeListener.beanUtilsBean`), would be nice to declare that fact properly.
=> shiro-guice depends on commons-beanutils

core/src/main/java/org/apache/shiro/authc/pam/FirstSuccessfulStrategy.java, core/src/test/java/org/apache/shiro/authc/pam/FirstSuccessfulStrategyTest.java
The '!' lost in the process of migration from 1.3.x to 1.4.0.
=> [SHIRO-660] Bug in FirstSuccessfulStrategy

core/src/main/java/org/apache/shiro/mgt/DefaultSecurityManager.java, core/src/test/java/org/apache/shiro/mgt/DefaultSecurityManagerTest.java
When one does not use a static SecurityManager an exception is thrown everytime a new (unauthenticated) subject successfully logs in. See the associated JIRA issue https://issues.apache.org/jira/browse/SHIRO-457
=> [SHIRO-457] Set SecurityManager in createSubject()

core/src/main/java/org/apache/shiro/authz/Permission.java
I corrected a typo in the javadoc for the Permission interface.
=> Fix typo in javadoc for Permission

core/src/main/java/org/apache/shiro/realm/AuthenticatingRealm.java, core/src/test/groovy/org/apache/shiro/realm/AuthenticatingRealmTest.groovy
Supercedes https://github.com/apache/shiro/pull/69
This fix the failing test.
=> [SHIRO-662] Constant Name Change in AuthenticationRealm

core/src/main/java/org/apache/shiro/subject/support/DelegatingSubject.java, web/src/main/java/org/apache/shiro/web/filter/authc/AuthenticationFilter.java
When session is based on servlet container(such as tomcat),if the subject is authenticated，the session will contains `AUTHENTICATED_SESSION_KEY` and `PRINCIPALS_SESSION_KEY`。
When servlet container closed, it may will be persist session.
But if the principal can not be serializable, it will not be persisted; when server restart, session will only contains `AUTHENTICATED_SESSION_KEY` info ,the `PRINCIPALS_SESSION_KEY` will be lost, 
it means the subject is authenticated, but the subject does not has principal。If the user code is 
```
User u = subject.getPrincipal();
// because the u if null, it will be npe
u.getName();
```
Recently, my project has happened such case, so I think add check for  principal of subject whether is null can make application more powerful.
=> [SHIRO-661] Add check for the principal of subject whether is null

pom.xml, support/hazelcast/pom.xml
Hazelcast should be updated as it carries a CVE:
hazelcast-3.7.2.jar (pkg:maven/com.hazelcast/hazelcast@3.7.2, cpe:2.3:a:hazelcast:hazelcast:3.7.2:::::::*) : CVE-2016-10750
=> SHIRO-695 - Update Hazelcast

integration-tests/guice3/pom.xml, integration-tests/guice4/pom.xml, integration-tests/support/pom.xml, pom.xml, samples/guice/pom.xml, samples/servlet-plugin/pom.xml, samples/spring-hibernate/pom.xml, samples/spring-mvc/pom.xml, samples/web/pom.xml, web/pom.xml
Remove old JSTL jars and replace with up-to-date Apache version, which doesn't have a CVE associated with it.
=> Remove old JSTL jars

core/src/main/java/org/apache/shiro/realm/jdbc/JdbcRealm.java, core/src/test/java/org/apache/shiro/realm/jdbc/JDBCRealmTest.java
This fixes [SPAP-552](https://issues.apache.org/jira/browse/SHIRO-552)
The change has been tested in https://github.com/steinarb/authservice/ and worked as a drop in replacement for the existing [AuthserviceDbRealm ](https://github.com/steinarb/authservice/blob/master/authservice.web.security.dbrealm/src/main/java/no/priv/bang/authservice/web/security/dbrealm/AuthserviceDbRealm.java#L25)
Note that the change makes JdbcRealm expect salt to be base64 encoded by default.  It is possible to get the original behaviour back, by setting the [JdbcRealm saltIsBase64Encoded property](https://github.com/steinarb/shiro/blob/shiro-jdbcrealm-bas64-coded-salt/core/src/main/java/org/apache/shiro/realm/jdbc/JdbcRealm.java#L214) to false.
=> [SHIRO-552] Support base64 encoded salt in JdbcRealm

config/core/src/main/java/org/apache/shiro/config/Ini.java, config/core/src/test/groovy/org/apache/shiro/config/IniTest.groovy
When fixing this issue, I found a bug in the `isCharEscaped` method and the `index` usage.
=> [SHIRO-684] INI parser keeps escape characters in keys and values

samples/aspectj/pom.xml, support/aspectj/pom.xml
The current aspectj maven plugin appears dead - so switch to use a fork which supports JDK 11
=> Get the aspectj modules passing with JDK 11

pom.xml, samples/jaxrs/pom.xml, samples/servlet-plugin/pom.xml
I couldn't get two of the samples working with JDK11, so this patch disables running those two samples with JDK11. I also updated the dependencies in the JAX-RS demo.
=> Get build working with JDK11

core/src/main/java/org/apache/shiro/authc/credential/DefaultPasswordService.java
Followed the steps as described in the ticket https://issues.apache.org/jira/browse/SHIRO-458
Replaced the string equals with an internal equals method.
I ran the unit tests and they have all passed
=> [SHIRO-458] Replaced string equals with internal method that does not leak time

support/spring/pom.xml, support/spring/src/main/java/org/apache/shiro/spring/web/config/AbstractShiroWebFilterConfiguration.java, support/spring/src/test/groovy/org/apache/shiro/spring/config/ShiroWebFilterConfigurationTest.groovy
In the days of XML this was defined, but was missed when we ported it to Java config
NOTE: This still needs tests. I put this in a PR so we wouldn't forget, but this was found based on a question from [StackOverflow](https://stackoverflow.com/questions/51552021/adding-custom-filter-apache-shiro-spring-boot).
=> [SHIRO-687] Adding Spring's Filters to ShiroFilterFactorBean when using Java config

support/servlet-plugin/src/main/resources/META-INF/web-fragment.xml
Enables async support for use of `@Suspended AsyncResponse`. Some Application Servers, like Liberty Profile, will throw a NullPointerException without this commit.
Signed-off-by: Benjamin Marwell <bmarwell@gmail.com>
=> [SHIRO-735] Enable servlet async support.

core/src/main/java/org/apache/shiro/realm/jdbc/JdbcRealm.java
Signed-off-by: Benjamin Marwell <bmarwell@gmail.com>
=> [SHIRO-469] (doc) correct javadoc for JdbcRealm#setPermissionQuery.

web/src/main/java/org/apache/shiro/web/filter/PathMatchingFilter.java, web/src/main/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolver.java, web/src/test/java/org/apache/shiro/web/filter/PathMatchingFilterTest.java, web/src/test/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolverTest.java
this bug due to my pr  [SHIRO-682 fix the potential threat when use "uri = uri + '/' " to bypassed shiro](https://github.com/apache/shiro/pull/127) in 1.5, sorry 
as the @jaynlau [comment](https://github.com/apache/shiro/pull/181)
under is @jaynlau report  
````
Can not get the NamedFilterList when request uri is "/".
java.lang.IllegalArgumentException: There is no configured chain under the name/key [].
at org.apache.shiro.web.filter.mgt.DefaultFilterChainManager.proxy(DefaultFilterChainManager.java:322) ~[shiro-web-1.5.0.jar:1.5.0]
at org.apache.shiro.web.filter.mgt.PathMatchingFilterChainResolver.getChain(PathMatchingFilterChainResolver.java:126) ~[shiro-web-1.5.0.jar:1.5.0]
at org.apache.shiro.web.servlet.AbstractShiroFilter.getExecutionChain(AbstractShiroFilter.java:415) …
```
=> [SHIRO-742]fix throw exception when request uri is /

core/src/main/java/org/apache/shiro/subject/SimplePrincipalCollection.java
The bug report is https://issues.apache.org/jira/browse/SHIRO-751?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17069374#comment-17069374
As suggested by Benjamin Marwell, I change the thrown exceptions of SimplePrincipalCollection#add and SimplePrincipalCollection#allAll
=> [SHIRO-751] SimplePrincipalMap and SimplePrincipalCollection throw different exceptions for the same problem

support/guice/src/test/java/org/apache/shiro/guice/web/FilterConfigTest.java, support/guice/src/test/java/org/apache/shiro/guice/web/ShiroWebModuleTest.java, support/guice/src/test/java/org/apache/shiro/guice/web/SimpleFilterChainResolverTest.java, web/src/main/java/org/apache/shiro/web/util/WebUtils.java, web/src/test/groovy/org/apache/shiro/web/util/WebUtilsTest.groovy, web/src/test/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolverTest.java
Servlet-Path + Path-Info is used instead
NOTE: some servlet containers will decode the context-path (Tomcat) and others will not (Jetty).  Per the Servlet spect the servlet-path and path-info are always decoded.
Shiro only makes decisions based on the application path, I.e. the request URI with the context-path removed, so we can just avoid dealing with it all together.
`WebUtils.getRequestURI()` has been deprecated to reflect this, and the previous behavior restored (as there was an issue with double decoding the URL in SHIRO-753)
Fixes: SHIRO-753
=> [SHIRO-753] The context path is no longer used when determining the path application path

core/src/main/java/org/apache/shiro/SecurityUtils.java
As it can be modified and read by different threads. This has been biting me for a very long time now.
=> [SHIRO-762] Mark `SecurityUtils.securityManager` as volatile

web/src/main/java/org/apache/shiro/web/mgt/CookieRememberMeManager.java, web/src/test/java/org/apache/shiro/web/mgt/CookieRememberMeManagerTest.java
=> [SHIRO-766] ignore exception on invalid cookies.

NOTICE, support/guice/src/main/java/org/apache/shiro/guice/web/ShiroWebModule.java, web/src/main/java/org/apache/shiro/web/filter/authz/IpAddressMatcher.java, web/src/main/java/org/apache/shiro/web/filter/authz/IpFilter.java, web/src/main/java/org/apache/shiro/web/filter/authz/IpSource.java, web/src/main/java/org/apache/shiro/web/filter/mgt/DefaultFilter.java, web/src/test/java/org/apache/shiro/web/filter/authz/IpAddressMatcherTests.java, web/src/test/java/org/apache/shiro/web/filter/authz/IpFilterTest.java
Resolved merge conflict from original PR #57 as per @fpapon recommendation.
=> [SHIRO-764] Add IpFilter for restricting access IP ranges

pom.xml, samples/jaxrs/pom.xml, support/jaxrs/pom.xml
- Non-Breaking change.
- Also set the scope to provided. Containers will provide this API.
- Also add the dependency to the samples, so they do not use a
transitive dependency.
=> [SHIRO-750] update jax-rs dependency to jakarta.

web/src/test/java/org/apache/shiro/web/mgt/CookieRememberMeManagerTest.java
Introduced by https://github.com/apache/shiro/pull/224
That PR's build job should have failed but apperently did not.
=> [SHIRO-770] Fix test regression introduced by SHIRO-770.

web/src/main/java/org/apache/shiro/web/env/EnvironmentLoader.java, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java, web/src/test/resources/EmptyShiroIni.ini
- Enables building with JDK11 and 14
- refactored ServiceLoader loading into separate method to enable mocking.
=> [SHIRO-772] Remove PowerMock from EnvironmentLoaderServiceTest.java.

crypto/cipher/src/main/java/org/apache/shiro/crypto/AesCipherService.java, pom.xml
- Updated groovy to 3.x. 2.5.10 would have been enough, but here were no failing tests due to the use of the new major version, so why not just update?
- Added an oversight from [SHIRO-736](https://issues.apache.org/jira/browse/SHIRO-736) where it was found out that the GCM padding cipher is just an alias for the non-padding one. It was only added for block mode ciphers. This is needed to get Shiro compiling with JDK14.
=> [SHIRO-773] update groovy for JDK14 builds.

pom.xml
- this is already covered by the enforcer plugin.
- Fixes https://issues.apache.org/jira/browse/SHIRO-774
=> [SHIRO-774] remove ignored prerequisites

pom.xml, support/hazelcast/src/main/java/org/apache/shiro/hazelcast/cache/HazelcastCacheManager.java, support/hazelcast/src/test/groovy/org/apache/shiro/hazelcast/cache/HazelcastCacheManagerTest.groovy, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java
This test will now actually start hazelcast. If this is not feasible, just add a corresponding comment to this PR.
=> [SHIRO-777] remove powermock.

integration-tests/support/pom.xml, pom.xml
* Removes JUnit 4
* Adds JUnit 5
* Adds junit jupiter vintage engine
Needs rebasing after https://github.com/apache/shiro/pull/236
=> [SHIRO-777] Update JUnit

core/src/main/java/org/apache/shiro/subject/support/DelegatingSubject.java, core/src/test/java/org/apache/shiro/subject/DelegatingSubjectTest.java
Fixes SHIRO-551.
I used StringJoiner instead of StringUtils.ToString, because the dependency to StringUtils is probably not needed anymore since Java 8.
=> [SHIRO-551] Implement toString() for DelegatingSubject.java.

support/spring/src/main/java/org/apache/shiro/spring/web/config/AbstractShiroWebFilterConfiguration.java, support/spring/src/test/groovy/org/apache/shiro/spring/config/ShiroWebConfigurationTest.groovy
filterMap should be not required, as this could be empty
=> [SHIRO-784] Fixed issue where no custom filters are defined in spring (non-boot) apps

config/ogdl/src/main/java/org/apache/shiro/config/ogdl/ReflectionBuilder.java, config/ogdl/src/test/groovy/org/apache/shiro/config/ogdl/ReflectionBuilderTest.groovy, config/ogdl/src/test/java/org/apache/shiro/config/ogdl/beans/InitCountBean.java
=> [SHIRO-778] onInit method on AuthenticatingRealm is called twice

core/src/main/java/org/apache/shiro/env/DefaultEnvironment.java, web/src/main/java/org/apache/shiro/web/env/IniWebEnvironment.java
=> [SHIRO-610] Allways create resolver for non-empty IniWebEnvironment

core/src/main/java/org/apache/shiro/session/mgt/AbstractValidatingSessionManager.java, core/src/main/java/org/apache/shiro/session/mgt/ExecutorServiceSessionValidationScheduler.java, core/src/test/java/org/apache/shiro/session/mgt/ExecutorServiceSessionValidationSchedulerTest.java
Closes SHIRO-398.
Refactored the variable name to be consistent across implementations.
=> [SHIRO-398] - Renamed the variable interval to sessionValidationInterval

web/src/main/java/org/apache/shiro/web/servlet/SimpleCookie.java
With Chrome increasing security of cookies not defining any SameSite options, the deleteMe cookie may be blocked by Chrome under some circumstances.
For example, when an app is used within a cross-site iframe, one must defined the option SameSite=None option. This works for the main cookie, but the deleteMe is currently blocked. This commit fixes this.
is to use the JIRA issue title in the pull request title and in the first line of …
=> [SHIRO-793] deleteMe cookie should use the defined "sameSite"

core/src/main/java/org/apache/shiro/realm/text/TextConfigurationRealm.java
Iterating over a map then looking up a key guarantees 2x the hash map lookups than what is necessary.  See [here](https://fbinfer.com/docs/next/all-issue-types#inefficient_keyset_iterator) for a more detailed writeup.
This instance was found [using the Muse analysis platform](https://console.muse.dev/result/ayorra/shiro/01EFG4TPKZ5KF3KARJ1HC79P3A?search=inefficient&tab=results) (which I work on), specifically with the Infer tool.  It appears Apache is pro-CI and the analysis worked out of the box and without configuration.  Perhaps we should [enable it](https://github.com/apps/muse-dev) to run on all pull requests, meaning new bugs would receive comments ([example](https://github.com/TomMD/shiro/pull/2)).
=> [No JIRA] Fix inefficient iterators

support/spring/src/main/java/org/apache/shiro/spring/web/config/AbstractShiroWebConfiguration.java, support/spring/src/test/groovy/org/apache/shiro/spring/web/config/ShiroWebConfigurationTest.groovy, support/spring/src/test/java/org/apache/shiro/spring/web/config/ShiroWebConfigurationTestSameSiteStrict.java, support/spring/src/test/resources/org/apache/shiro/spring/web/config/ShiroWebConfigurationTestSameSiteStrict.properties, web/src/main/java/org/apache/shiro/web/servlet/Cookie.java, web/src/main/java/org/apache/shiro/web/servlet/SimpleCookie.java
Functional changes:
- automatically set secure cookie on SameSiteOptions.NONE
- added test for the default value = LAX
- added test class for STRICT value
Other changes:
- add javadoc cookie description from developer.mozilla.org
- add missing overrides
- remove unused imports in AbstractShiroWebConfiguration and its test
Trivial …
=> [SHIRO-789] Add SameSite option to AbstractShiroWebConfiguration.buildCookie

support/spring-boot/spring-boot-starter/src/test/groovy/org/apache/shiro/spring/boot/autoconfigure/SpringFactoriesTest.groovy, support/spring-boot/spring-boot-web-starter/src/main/resources/META-INF/spring.factories, support/spring-boot/spring-boot-web-starter/src/test/groovy/org/apache/shiro/spring/boot/autoconfigure/web/WebSpringFactoriesTest.groovy
hotfix Springboot in versions lower than 2.0.7 does not have trim classname, one more space causes an error
https://issues.apache.org/jira/projects/SHIRO/issues/SHIRO-797?filter=allopenissues
=> [SHIRO-797] Shiro 1.7.0 is lower than using springboot version 2.0.7 dependency error

lang/src/main/java/org/apache/shiro/lang/io/DefaultSerializer.java
Hi, I would like to start by saying I am sorry for not following your community guidelines but since this patch is really tiny, I didn't think it would be necessary to create a task at Jira or follow the other procedures, if this is considered unnaceptable, do let me know and I will open this PR as specified. Thanks for the comprehension.
Flushes OutputStream before using the underlying ByteArrayOutputStream: when an OutputStream (or its subclass) instance is built on top of an underlying ByteArrayOutputStream instance, it should be flushed or closed before the underlying instance's toByteArray() is invoked. Failing to fulfill this requirement may cause toByteArray() to return incomplete contents.
=> Fix: flushes ByteArrayOutputStream before using

.github/workflows/maven.yml, pom.xml
=> (build) GitHub workflow

support/spring/src/test/groovy/org/apache/shiro/spring/web/config/ShiroWebConfigurationWithCacheTest.groovy
=> (no-issue) remove invalid and unused imports leading to a compile error.

.github/workflows/maven.yml, integration-tests/guice3/pom.xml, integration-tests/guice4/pom.xml, pom.xml, samples/guice/pom.xml, support/guice/pom.xml, support/guice/src/test/java/org/apache/shiro/guice/BeanTypeListenerTest.java, support/hazelcast/src/test/groovy/org/apache/shiro/hazelcast/cache/HazelcastCacheManagerTest.groovy, support/jaxrs/pom.xml, support/jaxrs/src/test/groovy/org/apache/shiro/web/jaxrs/ExceptionMapperTest.groovy, support/spring/src/test/groovy/org/apache/shiro/spring/config/ShiroEventBusAwareBeanPostProcessorTest.groovy, web/src/test/groovy/org/apache/shiro/web/servlet/ShiroHttpServletResponseTest.groovy, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java
* Replaced a few EasyMock tests with Mockito where needed.
* `--illegal-access=permit` for guice tests.
* Remove JDK17-ea for now, no groovy support.
---
If …
=> (build) fix JDK 16/17 builds

core/src/main/java/org/apache/shiro/realm/ldap/DefaultLdapContextFactory.java, core/src/main/java/org/apache/shiro/realm/ldap/JndiLdapContextFactory.java, core/src/main/java/org/apache/shiro/realm/ldap/LdapContextFactory.java, core/src/test/java/org/apache/shiro/realm/ldap/DefaultLdapContextFactoryTest.java, core/src/test/java/org/apache/shiro/realm/ldap/JndiLdapContextFactoryTest.java
- remove `public LdapContext getLdapContext(String username, String password)`
- remove now redundant casts
--- 
If this is your first contribution, you have …
=> [SHIRO-807] remove deprecated method signature

core/src/test/java/org/apache/shiro/concurrent/SubjectAwareExecutorServiceTest.java, core/src/test/java/org/apache/shiro/concurrent/SubjectAwareExecutorTest.java, web/src/main/java/org/apache/shiro/web/filter/authc/BasicHttpAuthenticationFilter.java, web/src/test/java/org/apache/shiro/web/WebTest.java, web/src/test/java/org/apache/shiro/web/filter/authc/BasicHttpFilterAuthenticationTest.java, web/src/test/java/org/apache/shiro/web/filter/authz/AuthorizationFilterTest.java, web/src/test/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolverTest.java, web/src/test/java/org/apache/shiro/web/mgt/DefaultWebSecurityManagerTest.java, web/src/test/java/org/apache/shiro/web/servlet/ShiroHttpServletRequestTest.java
This PR converts tests from the web project from using EasyMock into Mockito. 
The idea is that EasyMock creates mocks which seem unpredictable in a few cases we encounter, leading to flaky tests.
https://issues.apache.org/jira/browse/SHIRO-811
---
In …
=> [SHIRO-811] fix toggling test through Mockito conversion.

core/src/main/java/org/apache/shiro/realm/text/TextConfigurationRealm.java
=> Bugfix, fixed Scanner issue

config/core/src/main/java/org/apache/shiro/config/Ini.java, config/core/src/test/groovy/org/apache/shiro/config/IniTest.groovy
=> [SHIRO-812] Key value separator in config is broken with escape char

support/spring-boot/spring-boot-starter/src/main/java/org/apache/shiro/spring/boot/autoconfigure/ShiroAnnotationProcessorAutoConfiguration.java
If there is a spring-boot-starter-aop dependency in the project's classpath, Spring will automatically create a bean named "org.springframework.aop.config.internalAutoProxyCreator". 
This will cause Spring beans to be proxied twice. If one is a JDK dynamic proxy and the other is a CGLIB proxy, then the system will fail to start.
We may be able to avoid such errors by modifying the defaultAdvisorAutoProxyCreator method of the ShiroAnnotationProcessorAutoConfiguration class.
I have tested this modification in my own project and it works. Sorry, my English is not very good, this paragraph is written using Google Translate.
Spring boot log:
```html
ShiroAnnotationProcessorAutoConfiguration#defaultAdvisorAutoProxyCreator:
Did not match:
- @ConditionalOnMissingBean (names: …
```
=> [SHIRO-804] - Avoid conflicts with spring boot aop

config/ogdl/src/main/java/org/apache/shiro/config/ogdl/CommonsInterpolator.java
The stated behavior is not the observed.
This is a complement to: https://github.com/apache/shiro-site/pull/82
The relevant section of the [commons-configuration class](https://commons.apache.org/proper/commons-configuration/apidocs/org/apache/commons/configuration2/interpol/ConfigurationInterpolator.html) is:
> After an instance has been created *it does not contain any Lookup objects*. The current set of lookup objects can be modified using the registerLookup() and deregisterLookup() methods. *Default lookup objects (that are invoked for variables without a prefix)* can be added or removed with the addDefaultLookup() and removeDefaultLookup() methods respectively. (When a ConfigurationInterpolator instance is created by a configuration object, a default lookup object is added pointing …
=> [SHIRO-817] Update `CommonsInterpolator` doc to reflect actual behavior

web/src/main/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolver.java, web/src/test/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolverTest.java
=> backport SHIRO-825 to 1.8

web/src/main/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolver.java, web/src/test/java/org/apache/shiro/web/filter/mgt/PathMatchingFilterChainResolverTest.java
Fixes https://issues.apache.org/jira/browse/SHIRO-825: Trailing slash in URI results in "IllegalArgumentException: There is no configured chain under the name/key"
When the request URI has a trailing slash, but the pattern does not have a trailing slash (or vice versa), it is still supposed to match. However, when they don't match exactly, we enter the `else` branch where the call to `filterChainManager.proxy()` has the incorrect parameter! (When they match exactly, the call to `filterChainManager.proxy()` has the correct parameter -- see line 114).
This seems to be a copy/paste error introduced by commit https://github.com/apache/shiro/commit/ab1ea4a2006f6bd6a2b5f72740b7135662f8f160#diff-a724e4e5fde47ea6cc29803d5a4581a299b74f09d4ec5ce047e7d3e056116815R129
In Shiro 1.7.0, it didn't have …
=> [SHIRO-825] Fixes "IllegalArgumentException: There is no configured chain under the name/key"

web/src/main/java/org/apache/shiro/web/session/mgt/DefaultWebSessionManager.java, web/src/test/groovy/org/apache/shiro/web/session/mgt/DefaultWebSessionManagerTest.groovy
- `getParameters()` will also parse the body, which in turn decodes the content.
avoid calling this method unless we know the sessionID can be in the query part.
In this case, just format the pull request title like `(DOC) - Add javadoc in …
=> [SHIRO-678] only query parameters for sessionID if found

core/src/main/java/org/apache/shiro/authz/annotation/RequiresAuthentication.java, core/src/main/java/org/apache/shiro/authz/annotation/RequiresGuest.java, core/src/main/java/org/apache/shiro/authz/annotation/RequiresPermissions.java, core/src/main/java/org/apache/shiro/authz/annotation/RequiresRoles.java, core/src/main/java/org/apache/shiro/authz/annotation/RequiresUser.java, event/src/main/java/org/apache/shiro/event/Subscribe.java
Shiro annotations will now be included in generated Javadoc
Fixes: SHIRO-216
=> Add @Documented to Shiro annotations

.github/workflows/maven.yml, .jenkins.groovy, integration-tests/guice3/pom.xml, integration-tests/guice4/pom.xml, pom.xml, samples/guice/pom.xml, support/guice/pom.xml
=> [SHIRO-840] Java 17 support.

core/src/main/java/org/apache/shiro/mgt/SessionsSecurityManager.java
We see this NPE intermittently from KNOX when a topology is being redeployed and a request is still being processed in Shiro's AuthenticatingFilter.
```java
log.trace("Starting session for host {}", getHost());
SessionContext sessionContext = createSessionContext();
// At this point the topology deploy already triggered a securityManager.destroy() so sessionManager is null
Session session = this.securityManager.start(sessionContext);  // <- NPE comes from here
this.session = decorate(session); 
```
```I saw this while hitting Knox repeatedly during topology redeploys/restarts. There should never be a NPE.
2020-03-17 15:13:08,878 ERROR knox.gateway (AbstractGatewayFilter.java:doFilter(60)) - Failed to execute filter: javax.servlet.ServletException: java.lang.NullPointerException
2020-03-17 …
```
=> SHIRO-841 - NullPointerException from SessionsSecurityManager.start()

samples/web/pom.xml
On mvn jetty:run in the samples/web,  java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter  shows up. This PR resolves the error.
=> Fix SHIRO-881

core/src/test/java/org/apache/shiro/authz/aop/PermissionAnnotationHandlerTest.java, core/src/test/java/org/apache/shiro/authz/aop/RoleAnnotationHandlerTest.java, core/src/test/java/org/apache/shiro/concurrent/SubjectAwareExecutorServiceTest.java, core/src/test/java/org/apache/shiro/concurrent/SubjectAwareExecutorTest.java, core/src/test/java/org/apache/shiro/test/SecurityManagerTestSupport.java, web/src/test/groovy/org/apache/shiro/web/filter/authc/BearerHttpFilterAuthenticationTest.groovy, web/src/test/java/org/apache/shiro/web/filter/authc/BasicHttpFilterAuthenticationTest.java, web/src/test/java/org/apache/shiro/web/filter/authz/AuthorizationFilterTest.java
Individual test methods can scope the usage of a SecurityManger and Subject to specific methods.
Related to: #361
=> Reduce the scope of the ThreadLocals used in SecurityManagerTestSupport

core/src/main/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealm.java, core/src/main/java/org/apache/shiro/realm/ldap/AbstractLdapRealm.java, core/src/test/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealmTest.java
=> [SHIRO-871] Apply principalSuffix only when username does NOT already contain the suffix

core/src/main/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealm.java, core/src/main/java/org/apache/shiro/realm/ldap/AbstractLdapRealm.java, core/src/test/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealmTest.java
=> Apply principalSuffix only when username does NOT already contain the suffix

core/src/main/java/org/apache/shiro/subject/support/DelegatingSubject.java
Fixes [SHIRO-512](https://issues.apache.org/jira/browse/SHIRO-512)
Fixes https://github.com/flowlogix/flowlogix/issues/284
If this is your first contribution, …
=> [SHIRO-512] catch SessionException in getRunAsPrincipalsStack

crypto/cipher/pom.xml, crypto/hash/pom.xml, integration-tests/jaxrs/app/pom.xml, integration-tests/jaxrs/meecrowave/pom.xml, integration-tests/jaxrs/openliberty/pom.xml, integration-tests/jaxrs/pom.xml, integration-tests/jaxrs/tests/pom.xml, integration-tests/meecrowave-support/pom.xml, pom.xml, samples/jaxrs/pom.xml
- Fix integration test package versions
- Update various dependencies: …
=> Update Deps for 1.10.x

lang/src/main/java/org/apache/shiro/util/StringUtils.java, lang/src/test/java/org/apache/shiro/lang/util/StringUtilsTest.java, web/src/main/java/org/apache/shiro/web/filter/authc/FormAuthenticationFilter.java, web/src/main/java/org/apache/shiro/web/util/WebUtils.java
Fixes SHIRO-887.
This PR fixes an issue where passwords which start and/or end with spaces are trimmed by the FormAuthenticationFilter, which prevents login for users with such passwords.
**Note:** I am a first time contributor, so I have no CLA signed yet. In order to fulfill the contribution guidelines, I have sent the signed CLA to the Apache Software Foundations secretary office.
**Update 2022/07/30:** CLA is acknowledge.
---
is …
=> [SHIRO-887] Do not trim passwords in FormAuthenticationFilter

integration-tests/pom.xml, pom.xml
- Update guava to 31.1
- Add optional flag to skip dependency check for integration tets
=> update guava 1 10 x

pom.xml
The newer version attempts to resolve dependencies that are not available (or use in a report)
=> Revert: Bump maven-project-info-reports-plugin from 3.1.2 to 3.4.1

support/spring-boot/spring-boot-starter/pom.xml, support/spring-boot/spring-boot-starter/src/main/java/org/apache/shiro/spring/boot/autoconfigure/ShiroAnnotationProcessorAutoConfiguration.java, support/spring-boot/spring-boot-starter/src/test/groovy/org/apache/shiro/spring/boot/autoconfigure/AspectjAndDefaultProxyCreatorTest.groovy, support/spring-boot/spring-boot-starter/src/test/groovy/org/apache/shiro/spring/boot/autoconfigure/ShiroAnnotationProcessorAutoConfigurationTest.groovy, support/spring-boot/spring-boot-starter/src/test/java/org/apache/shiro/spring/boot/autoconfigure/AspectjAndDefaultProxyCreatorApplication.java, support/spring-boot/spring-boot-starter/src/test/java/org/apache/shiro/spring/boot/autoconfigure/AspectjEnabledApplication.java
See #268  for the previous fix.  But when `@EnableAspectJAutoProxy` enabled, spring actually creates an instance of  `AnnotationAwareAspectJAutoProxyCreator` but not `DefaultAdvisorAutoProxyCreator`.  In this situation, there will be two proxy creators in the same context, which leads to methods be proxied twice also .
The fix may just remove the type value of the `@ConditionalOnMissingBean`.
```
@Bean
@DependsOn("lifecycleBeanPostProcessor")
@ConditionalOnMissingBean(name = AopConfigUtils.AUTO_PROXY_CREATOR_BEAN_NAME)
@Override
public DefaultAdvisorAutoProxyCreator defaultAdvisorAutoProxyCreator() {
return super.defaultAdvisorAutoProxyCreator();
}
```
=> [SHIRO-890] Avoid another proxy creator when @EnableAspectJAutoProxy enabled

.github/workflows/maven.yml, integration-tests/guice3/pom.xml, integration-tests/guice4/pom.xml, pom.xml, samples/guice/pom.xml, support/guice/pom.xml, support/hazelcast/pom.xml
This is based on #506, so that should get merged first. 
The additional commit will pull in changes from main (`--add-opens` and `--illegal-access`) where appropriate.
This commit will also change the github CI to use Java 17.
Mac will build on 8 and 17 only to save resources.
---
Trivial changes like typos do not require a JIRA …
=> [SHIRO-895] Workaround Guice Java17 compat and run tests on 17.

web/src/main/java/org/apache/shiro/web/env/DefaultWebEnvironment.java, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java
Fixes [SHIRO-893](https://issues.apache.org/jira/browse/SHIRO-893).
In 1.10.0, an NPE can be thrown because DefaultWebEnvironment has no default value for ShiroFilterConfiguration. This commit adds a default value determined by WebEnvironment.getShiroFilterConfiguration().
=> [SHIRO-893] - Fix NPE in ShiroFilter.init()

support/guice/src/main/java/org/apache/shiro/guice/web/GuiceShiroFilter.java, support/guice/src/main/java/org/apache/shiro/guice/web/ShiroWebModule.java, support/guice/src/main/java/org/apache/shiro/guice/web/WebGuiceEnvironment.java, support/guice/src/test/java/org/apache/shiro/guice/web/ShiroWebModuleTest.java
GuiceShiroFilter uses com.google.inject.Inject to conform with other usages
=> SHIRO-892 Ensure ShiroWebModules works with explicit bindings in with Guice

pom.xml, samples/servlet-plugin/pom.xml, src/japicmp/postAnalysisScript.groovy, support/guice/src/main/java/org/apache/shiro/guice/web/GuiceShiroFilter.java, support/guice/src/main/java/org/apache/shiro/guice/web/WebGuiceEnvironment.java, support/guice/src/test/java/org/apache/shiro/guice/web/GuiceShiroFilterTest.java, support/guice/src/test/java/org/apache/shiro/guice/web/ShiroWebModuleTest.java, support/guice/src/test/java/org/apache/shiro/guice/web/WebGuiceEnvironmentTest.java, support/spring/src/main/java/org/apache/shiro/spring/web/ShiroFilterFactoryBean.java, support/spring/src/main/java/org/apache/shiro/spring/web/config/AbstractShiroWebFilterConfiguration.java, web/src/main/java/org/apache/shiro/web/config/ShiroFilterConfiguration.java, web/src/main/java/org/apache/shiro/web/env/DefaultWebEnvironment.java, web/src/main/java/org/apache/shiro/web/env/IniWebEnvironment.java, web/src/main/java/org/apache/shiro/web/env/MutableWebEnvironment.java, web/src/main/java/org/apache/shiro/web/env/WebEnvironment.java, web/src/main/java/org/apache/shiro/web/servlet/AbstractShiroFilter.java, web/src/main/java/org/apache/shiro/web/servlet/OncePerRequestFilter.java, web/src/main/java/org/apache/shiro/web/servlet/ShiroFilter.java, web/src/test/groovy/org/apache/shiro/web/env/IniWebEnvironmentTest.groovy, web/src/test/groovy/org/apache/shiro/web/env/MockWebEnvironment.groovy, web/src/test/groovy/org/apache/shiro/web/servlet/ShiroFilterTest.groovy, web/src/test/java/org/apache/shiro/web/env/WebEnvironmentStub.java, web/src/test/java/org/apache/shiro/web/servlet/OncePerRequestFilterTest.java
Adds new ShiroFilterConfiguration class exposed through the WebEnvironment
This class allows for confiuration of the Shiro filter through various config mechanisms (Ini, Guice, Spring, etc)
This makes it easer to enable a static security manager when using Shiro's Servlet fragment, as now a web.xml is not required
Backport: 28e10e0ca1cdcd2cede86802fde8464b29265fc8
=> Allow for direct configuration of ShiroFilter through WebEnvironment

web/src/main/java/org/apache/shiro/web/env/DefaultWebEnvironment.java, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java
This is a forward-port of https://github.com/apache/shiro/pull/499 to main
----
In 1.10.0, an NPE can be thrown because DefaultWebEnvironment has no default value for ShiroFilterConfiguration. This commit adds a default value determined by WebEnvironment.getShiroFilterConfiguration().
Trivial changes like typos do not require a JIRA …
=> [SHIRO-893] Fix NPE in ShiroFilter.init()

web/src/main/java/org/apache/shiro/web/filter/InvalidRequestFilter.java, web/src/main/java/org/apache/shiro/web/util/WebUtils.java, web/src/test/java/org/apache/shiro/web/RestoreSystemProperties.java
Change the acquisition of system attributes to static variables to reduce congestion in high concurrency environments. The Boolean.getBoolean method  will call Hashtable to obtain system propertys ,and will lock.
In this case, just format the pull …
=> Performance optimization

pom.xml, web/src/main/java/org/apache/shiro/web/servlet/HttpSessionContext.java
…age and out of jakarta package to made Java modules work,
and avoid split package issues
1.11.x PR, same as #557 
If this is your first contribution, you have …
=> [SHIRO-899] moved the HttpSessionContext Jakarta shim into Shiro pack… (1.11.x)

pom.xml, support/features/src/main/resources/features.xml, support/jcache/pom.xml, support/jcache/src/main/java/org/apache/shiro/cache/jcache/JCacheManager.java, support/jcache/src/main/resources/META-INF/NOTICE, support/jcache/src/test/groovy/org/apache/shiro/cache/jcache/JCacheManagerTest.groovy, support/pom.xml
Supersedes https://github.com/apache/shiro/pull/332
`This will allow for any JCache implementation to work with Shiro, as well as new versions of EhCache & Hazelcast.`
=> [SHIRO-849] Add cache module for JCache

config/ogdl/src/main/java/org/apache/shiro/config/ogdl/ReflectionBuilder.java
Currently, if I have a bean with a fluent setter (meaning it does not return `void` but `this`), it is ignored in my `shiro.ini` file.
This PR fixes the problem.
I found out the issue when upgrading buji-pac4j to pac4j v6. Here is the local patch: https://github.com/bujiio/buji-pac4j/commit/6fb21b1a7b051609f78c377d7bd3eae168875c7f#diff-ab7750a1c3bbcd663e2b0750f1ac11eac16b93c7ef5da9b8eb43af3d90ef7868R95
=> Properly handle fluent setters

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_related.yml, .github/ISSUE_TEMPLATE/enhancement_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
Resolve #897 by adding bug report, documentation related, enhancement request, feature request, and question issue templates.
If this is your first …
=> [#897] - Add issue templates

pom.xml
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/shiro/README.md
and https://issues.apache.org/jira/browse/FELIX-6602
notice: this PR should be back-ported to 1.x also...
=> upgrade m-bundle-p: solves last Reproducible Builds issue

integration-tests/jakarta-ee/pom.xml, integration-tests/jaxrs/tests/pom.xml, pom.xml, samples/spring-boot-3-web/pom.xml, support/cdi/pom.xml, support/jakarta-ee/pom.xml, support/spring-boot/pom.xml
=> deps: update minor versions of depdencies that dependabot missed

integration-tests/guice3/pom.xml, integration-tests/guice3/src/test/java/org/apache/shiro/samples/guice/ContainerIntegrationIT.java, integration-tests/guice4/pom.xml, integration-tests/guice4/src/test/java/org/apache/shiro/samples/guice/ContainerIntegrationIT.java, integration-tests/support/pom.xml, integration-tests/support/src/main/java/org/apache/shiro/testing/web/AbstractContainerIT.java, pom.xml, samples/guice/pom.xml, samples/guice/src/test/java/org/apache/shiro/samples/guice/ContainerIntegrationIT.java, samples/servlet-plugin/pom.xml, samples/servlet-plugin/src/test/java/org/apache/shiro/test/ContainerIntegrationIT.java, samples/spring-hibernate/pom.xml, samples/spring-hibernate/src/test/java/org/apache/shiro/samples/ContainerIntegrationIT.java, samples/web/pom.xml, samples/web/src/test/java/org/apache/shiro/test/WebAppContainerIntegrationIT.java
=> [#1010] deps: updated htmlunit to 3.5.0

web/src/main/java/org/apache/shiro/web/mgt/CookieRememberMeManager.java, web/src/test/java/org/apache/shiro/web/mgt/CookieRememberMeManagerTest.java
Issue 1048
The cookie value sometimes got too much '=' characters at the end.
I created a test to make the method fail, then I solved the problem. That fixed the test and made the RememberMe work again.
=> #1048: Solved base64 problem with remember me cookie.

support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/AuthenticationFilterDelegate.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/FormResubmitSupport.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/FormResubmitSupportCookies.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/Forms.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/listeners/EnvironmentLoaderListener.java
=> [#1079] - bugfix: make sure form resubmit cookie is secure

.github/workflows/maven.yml, .jenkins.groovy
=> [#1097] enh(build,ci,jdk): run on jdk 11, 17, and 21

pom.xml
Running the UTs and ITs durring the release process fails due to what looks like a classloader issue
This can be reproduce outside of the release process by running a build by running something like an "mvn verify site site:stage"
Could be a different classloader, ordering, or modulepath issue?
NOTE: I'm not a fan disabling tests durring the release, but I've spent too much time troubleshooting this issue.
=> Skipping tests while running release

support/cdi/src/test/java/org/apache/shiro/cdi/AnnotatedTypeWrapperTest.java
=> [Test] Refactored test to use utility function to get annotation instead of array indexing

crypto/hash/pom.xml, crypto/support/hashes/argon2/pom.xml, crypto/support/hashes/bcrypt/pom.xml
fixes https://github.com/apache/shiro/issues/1117 …
=> [#1117] fix missing osgi headers

tools/hasher/src/main/resources/log4j2.xml
When using the utility, I noticed that the logs were displayed incorrectly. 
I found a similar problem in Jira, but I think the `[INFO ]` output is correct, but the space after it is a consequence of incorrect logger settings, which I corrected.
Also update log message.
JIRA issue https://issues.apache.org/jira/browse/SHIRO-820
for the change (usually before you start working on it). Trivial changes like typos do not
require a JIRA issue. Your pull request should address just this issue, without pulling in other changes.
Trivial …
=> [SHIRO-820] - Fix Log4j2 logs format

core/src/test/java/org/apache/shiro/authz/permission/DomainPermissionTest.java, core/src/test/java/org/apache/shiro/concurrent/SubjectAwareExecutorServiceTest.java, core/src/test/java/org/apache/shiro/mgt/DefaultSecurityManagerTest.java, core/src/test/java/org/apache/shiro/mgt/VMSingletonDefaultSecurityManagerTest.java, core/src/test/java/org/apache/shiro/realm/AuthorizingRealmTest.java, core/src/test/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealmTest.java, core/src/test/java/org/apache/shiro/realm/jdbc/JDBCRealmTest.java, core/src/test/java/org/apache/shiro/session/mgt/DelegatingSessionTest.java, core/src/test/java/org/apache/shiro/session/mgt/ExecutorServiceSessionValidationSchedulerTest.java, core/src/test/java/org/apache/shiro/subject/DelegatingSubjectTest.java, core/src/test/java/org/apache/shiro/util/AntPathMatcherTests.java, lang/src/test/java/org/apache/shiro/lang/util/ClassUtilsTest.java, samples/aspectj/src/test/java/org/apache/shiro/samples/aspectj/bank/SecureBankServiceTest.java, samples/web-jakarta/src/test/java/org/apache/shiro/test/web/jakarta/WebContainerIT.java, support/ehcache/src/test/java/org/apache/shiro/cache/ehcache/EhCacheManagerTest.java, support/spring/src/test/java/org/apache/shiro/spring/web/ShiroFilterFactoryBeanTest.java, web/src/test/java/org/apache/shiro/web/env/EnvironmentLoaderServiceTest.java, web/src/test/java/org/apache/shiro/web/filter/authz/HttpMethodPermissionFilterTest.java, web/src/test/java/org/apache/shiro/web/filter/mgt/SimpleNamedFilterListTest.java, web/src/test/java/org/apache/shiro/web/mgt/DefaultWebSecurityManagerTest.java
=> [SHIRO-776] refactor: JUnit5 Best Practices

integration-tests/jaxrs/tests/src/main/java/org/apache/shiro/testing/jaxrs/tests/AbstractShiroJaxRsIT.java, support/jaxrs/src/main/java/org/apache/shiro/web/jaxrs/ShiroFeature.java
Changed registration of `UnauthenticatedException.class` to  `UnauthenticatedExceptionMapper.class `Jax-rs feature context.
fixes #1383
If this is your …
=> [#1383] bugfix: fix exception mapper type from registered features

core/src/main/java/org/apache/shiro/mgt/DefaultSecurityManager.java, core/src/test/java/org/apache/shiro/mgt/DefaultSecurityManagerTest.java
I didn't create a GitHub issue but there is [one in Jira](https://issues.apache.org/jira/browse/SHIRO-875). This PR fixes it.
=> [#SHIRO-875] Fix creating subjects with disabled session-creation

core/pom.xml, core/src/main/java/org/apache/shiro/SecurityUtils.java, core/src/main/java/org/apache/shiro/mgt/WrappedSecurityManager.java, core/src/test/java/org/apache/shiro/SecurityUtilsUnwrapTest.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/FormResubmitSupport.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/ShiroFilter.java
Jakarta EE module has to decorate `SecurityManager` since SecurityManager is designed to be customized / inherited by the user.
In order to do this, it introduced `WrappedSecurityManager`
Unfortunately, `SecurityUtils` classes would return the `WrappedSecurityManager` instance and there is no way to return the original customized `SecurityManager` as WrappedSecurityManager is not a superclass of the customized SecurityManager
This PR introduces `SecurityUtils.getSecurityManager(Class<> type)` to avoid casts to custom `SecurityManager` implementations by the user and unwraps the original if necessary
- Added `getSecurityManager(Class<> type)` that returns typed / unwrapped SM, or an exception to `SecurityUtils`
- Added `isSecurityManagerTypeOf(Class<> type)` to `SecurityUtils`
- Added …
=> [#1424] Add generic way to decorate SecurityManager

core/src/main/java/org/apache/shiro/mgt/DefaultSecurityManager.java, core/src/test/java/org/apache/shiro/mgt/DefaultSecurityManagerTest.java
I'm not sure if I had to remove the PR template after I've read it and made sure I followed everything in it. Perhaps you might want to note that in it.
This continues the work done in #1407. I didn't think of that case in it so this PR fixes it. I didn't open a new issue for it, sorry, I guess we could reuse the old one as it's a similar case.
cc @lprimak
=> [#SHIRO-875] Fix creating subjects from a `SubjectFactory` that disables session-creation

.github/workflows/maven.yml, .jenkins.groovy, tools/hasher/src/main/java/org/apache/shiro/tools/hasher/Hasher.java
Added `isTerminal()` check to Hasher tool, as JDK 22 changed console functionality
Run JDK 22 in CI
fixes #1381 
If this is your first contribution, you …
=> [#1381] enh: Build on JDK 22

core/src/main/java/org/apache/shiro/authc/SimpleAuthenticationInfo.java, core/src/main/java/org/apache/shiro/subject/ImmutablePrincipalCollection.java, core/src/main/java/org/apache/shiro/subject/MutablePrincipalCollection.java, core/src/main/java/org/apache/shiro/subject/PrincipalCollection.java, core/src/main/java/org/apache/shiro/subject/SimplePrincipalCollection.java, core/src/test/java/org/apache/shiro/subject/ImmutablePrincipalCollectionTest.java
Closes #1548. Declare PrincipalCollection interface to be intended to be immutable; provide an immutable implementation including a builder class; deprecate the mutable implementation; use the immutable one in SimpleAuthenticationInfo for merging.
Background: Merging AuthenticationInfo and the contained PrincipalCollections previously lead to one of the involved PrincipalCollections be selected by undefined means and being mutated, propagating the changes to other callers that did not expect such changes, including the authentication cache.
require a GitHub issue.  Your pull request should address just this …
=> [#1548] - redefines PrincipalCollection interface to be intended as immutable

support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/FormAuthenticationFilter.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/Forms.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/filters/ShiroFilter.java, support/jakarta-ee/src/main/java/org/apache/shiro/ee/listeners/EnvironmentLoaderListener.java
- Rewriting Servlet `redirect` responses to follow the request scheme taken from the proxy server
- Added `org.apache.shiro.ee.redirect.disabled` parameter in web.xml to disable this behavior
fixes #1762
In this case, just format the pull request …
=> [#1762] enh: follow desired request scheme when doing redirection

support/pom.xml, support/quartz/src/main/java/org/apache/shiro/session/mgt/quartz/QuartzSessionValidationJob.java, support/quartz/src/main/java/org/apache/shiro/session/mgt/quartz/QuartzSessionValidationScheduler.java, support/quartz/src/main/java/org/apache/shiro/session/mgt/quartz/package-info.java, support/quartz/src/main/resources/META-INF/NOTICE, test-coverage/pom.xml
IBM / Red Hat bought Terracotta assets including Quartz module. It has been resurrected and is now actively maintained again.
Reverts apache/shiro#1581
=> Revert "[#1499] - Deleted Quartz module."

core/src/main/java/org/apache/shiro/authc/credential/CredentialsMatcher.java, core/src/main/java/org/apache/shiro/authc/credential/HashedCredentialsMatcher.java, core/src/main/java/org/apache/shiro/authz/AuthorizationInfo.java, core/src/main/java/org/apache/shiro/authz/ModularRealmAuthorizer.java, core/src/main/java/org/apache/shiro/realm/ldap/LdapUtils.java, core/src/main/java/org/apache/shiro/session/mgt/eis/SessionDAO.java, core/src/main/java/org/apache/shiro/subject/Subject.java, core/src/main/java/org/apache/shiro/util/JavaEnvironment.java
The Javadoc contained invalid syntax for links.
Some code elements were not closed leading to text not appearing in the help.
Some examples of errors in the current documentation:
In this case, just format the pull request title like `[DOC] - Add …
=> [DOC] - Clean up invalid Javadoc syntax and broken references

crypto/hash/src/main/java/org/apache/shiro/crypto/hash/DefaultHashService.java
Found a redundant Optional check in DefaultHashService class. The current implementation checks if Optional is present (isPresent()) before accessing its value, which is unnecessary as the subsequent method already safely handles null values.
- Removed redundant isPresent() check in DefaultHashService
- Simplified code flow while maintaining the same functionality
This change improves code readability by avoiding unnecessary conditional checks without changing the behavior. Redundant Optional checks make the code more complex and potentially misleading.
Ran `mvn verify` to ensure basic checks pass. This change does not affect existing functionality, and all tests continue to pass.
---
=> Fix redundant Optional check in DefaultHashService

.github/workflows/maven.yml, .jenkins.groovy
=> chore(ci): update CI JDK 23 to 24

integration-tests/jakarta-ee/src/test/java/org/apache/shiro/testing/jakarta/ee/ShiroBeansIT.java, web/src/main/java/org/apache/shiro/web/filter/mgt/FilterChainManager.java, web/src/main/java/org/apache/shiro/web/mgt/DefaultWebSubjectFactory.java
for the change (usually before you start working on it).  Trivial changes like typos do not
Trivial changes like typos do not require a GitHub issue (javadoc, comments...).
If your pull …
=> chore(java): fix spelling
